const data = [
  {
    name: "ck6n",
    antennaMachineBandFail: 98,
    fingerprintModuleMismatch: 25,
    earphoneSilent: 0,
    sideKeyFail: 0,
    simCardNotDetected: 0,
    speakersNoiseLowVolume: 18,
    backCameraFuzziness: 0,
    nfcCardIdentificationTest: 3,
    indicatorLightFlashNotBrightWeak: 0,
  },
  {
    name: "x6525",
    antennaMachineBandFail: 2441,
    fingerprintModuleMismatch: 143,
    earphoneSilent: 101,
    sideKeyFail: 104,
    simCardNotDetected: 4,
    speakersNoiseLowVolume: 715,
    backCameraFuzziness: 77,
    nfcCardIdentificationTest: 0,
    indicatorLightFlashNotBrightWeak: 214,
  },
  {
    name: "KJ5",
    antennaMachineBandFail: 908,
    fingerprintModuleMismatch: 19,
    earphoneSilent: 46,
    sideKeyFail: 62,
    simCardNotDetected: 5,
    speakersNoiseLowVolume: 190,
    backCameraFuzziness: 183,
    nfcCardIdentificationTest: 0,
    indicatorLightFlashNotBrightWeak: 67,
  },
  {
    name: "cl6",
    antennaMachineBandFail: 501,
    fingerprintModuleMismatch: 0,
    earphoneSilent: 26,
    sideKeyFail: 26,
    simCardNotDetected: 1,
    speakersNoiseLowVolume: 63,
    backCameraFuzziness: 13,
    nfcCardIdentificationTest: 23,
    indicatorLightFlashNotBrightWeak: 42,
  },
  {
    name: "x836",
    antennaMachineBandFail: 669,
    fingerprintModuleMismatch: 15,
    earphoneSilent: 23,
    sideKeyFail: 57,
    simCardNotDetected: 1,
    speakersNoiseLowVolume: 79,
    backCameraFuzziness: 101,
    nfcCardIdentificationTest: 31,
    indicatorLightFlashNotBrightWeak: 26,
  },
  {
    name: "a663lc",
    antennaMachineBandFail: 468,
    fingerprintModuleMismatch: 17,
    earphoneSilent: 10,
    sideKeyFail: 2,
    simCardNotDetected: 2,
    speakersNoiseLowVolume: 81,
    backCameraFuzziness: 18,
    nfcCardIdentificationTest: 0,
    indicatorLightFlashNotBrightWeak: 1,
  },
];

export default data;
